### ISSUE TITLE
A question regarding Assignment 1

### ISSUE THREAD

**Issue by nerdizzyz** [UC-MACSS/persp-analysis_A18#10]
Hi, I would like to know whether the "Contributor 1" and "Contributor 2" also have to update their repositories after all the work is done by fetching and merging. 

Thanks in advance!

**Comment by jmausolf** [comment]
In general, it is good practice to fetch and merge updates of repositories you fork. As far as grading, we will only be considering the main repositories of the core developers as representative of the group assignment.
