### ISSUE TITLE
How to deal with voicemail and company's numbers? 

### ISSUE THREAD

**Issue by sanittawan** [UC-MACSS/persp-analysis_A18#19]
I've made phone calls to around half of the numbers on my list and so far only 14% of the numbers are valid numbers. By valid, I mean the calls can be connected, somebody answered the calls or they went to mailboxes. Among that 14 %, I have experienced hangups or refusal which mean Response = 0. It seems that unfortunately, the majority of the numbers (so far) are not valid numbers. Should I attempt to make a second phone call to numbers that went to mailboxes? 

On a separate matter, should I ignore numbers that belong to companies? I have called a number that has an automated phone answering system giving me an option to speak with an operator, but I am guessing that it's not the purpose of this survey.  

Thank you in advance!

**Comment by tonofshell** [comment]
I also wonder if by calling from an out-of-state number, if that's keeping many of the people in those valid numbers from even picking up. Many phone scammers these days generate a fake number with the same area code and 3 middle numbers as the number they're calling, as people seem to be more likely to pick up a call from a number that seems "local".

I don't believe it's legal to spoof a phone number, but we might see more success with converting valid numbers to pick-ups by making the calls from a number with the same area code. A VOIP service like Google Voice, that would allow you to pick an available number in any area code, would probably be the best way to go about accomplishing that. It would definitely be interesting to try after making some calls from a personal number and see if there's any effect.

**Comment by rickecon** [comment]
@sanittawan You definitely only need to attempt to call each number once. Just do the assignment with whatever response rate you get. For this assignment, I really don't care about the result, i.e., the correlation between age and 2016 voting choice. I just want you to get some experience collecting survey data. It makes a lot of the ideas concrete about sample selection, response rates, and post stratification.

**Comment by rickecon** [comment]
@tonofshell Don't set up a spoof number for this assignment. If there is any deception it could jeopardize my ability to assign this.
