### ISSUE TITLE
Filter out invalid phone numbers

### ISSUE THREAD

**Issue by liu431** [UC-MACSS/persp-analysis_A18#22]
I notice there are some websites where you can validate the phone numbers. This could be useful for filtering out invalid and out-of-service numbers. I used one called "numverify". When you type in a number, it will provide a JSON file containing the carrier, validate or not, location, etc. In order to validate 200 numbers, I wrote a simple function to scrape the JSON files and added a label to the numbers. Check out [this ](https://github.com/liu431/persp-analysis_A18/blob/master/Assignments/A4/Phone%20Numbers%20Validation%20Tool%20using%20NumVerify%20API.ipynb) if you have not called yet. Cheers!

**Comment by smiklin** [comment]
Thanks for this @liu431 !
I wrote this up in R— find it [here](https://github.com/smiklin/persp-analysis_A18/blob/master/Assignments/A4/phone%20numbers/README.md) if you're interested.

**Comment by liu431** [comment]
@smiklin Great! How does this work for your numbers?
When I just conditioned on "valid"==true, only 15 are filtered out. Then I looked at these JSON lists again and added more conditions that carriers, locations, line_type are not empty. Then 140 of them are invalid.

**Comment by smiklin** [comment]
Only a few got three that were "valid" == FALSE, and those are the three that have empty 'line_type'.
If carrier/location are empty though, does that mean an invalid number, or is it simply unknown/missing data?

**Comment by liu431** [comment]
From reading the JSON Formatting part of the documentation, I think the ones with missing information are likely to be fake (without identity authentication). I tried dialing some and none was successful.

**Comment by smiklin** [comment]
Oh, that is useful!  I might have to get a new key and re-run it. I decided not to call over the weekend so I'll see tomorrow!

**Comment by smiklin** [comment]
Hah, turns out the majority of numbers are not in service, and that is not something registered by numverify... Still it was good practice writing the code :-)
