### ISSUE TITLE
A very minor question about Assignment 1

### ISSUE THREAD

**Issue by jtschoi** [UC-MACSS/persp-analysis_A18#8]
Throughout the assignment's Question 2, we are asked to work with `DescrStats.py`. However, it is noticeable that the name of the file that is actually uploaded (to the main repo) is `DescrStat.py`. Can we assume that this is a typo and work with either `DescrStats.py` or `DescrStat.py` depending on whether groups changed file names afterwards?

Thank you!

**Comment by liu431** [comment]
Good catch! I think this is just a typo.

**Comment by Bobicheng-Zhang** [comment]
It should just be a typo.
I am having issues adding the .gitignore file. I don't see it locally after cloning. Is anyone else experiencing the same problem?

**Comment by nnickels** [comment]
The reason it's not showing up locally is because it's a hidden file (begins with .). You could edit the settings on your computer finder to show all types of file extensions - this would allow the .gitignore file that you cloned to your local machine to appear in your local repository.

**Comment by liu431** [comment]
It is the file without the title.

**Comment by Bobicheng-Zhang** [comment]
Found it. Thank you!
I used the terminal to show all hidden files and finally saw it.

**Comment by jtschoi** [comment]
Thank you!
